pipeline:

  test:
    image: node:alpine
    commands:
      - npm install -s
      - npm test

  docker:
    image: plugins/docker
    repo: pinked/visonic_control
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]

  deploy:
    image: docker
    secrets: [ USER_CODE, PANEL_WEB_NAME, HOST, USER_ID, REFRESH, SECRET ]
    commands:
      - docker deploy --compose-file docker-compose.yml visonic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock