version: "3"
services:
  visonic:
    networks:
      - proxy
    read_only: true
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.40'
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    image: pinked/visonic_control:${DRONE_BUILD_NUMBER}
    environment:
      - USER_CODE=${USER_CODE}
      - PANEL_WEB_NAME=${PANEL_WEB_NAME}
      - HOST=${HOST}
      - USER_ID=${USER_ID}
      - REFRESH=20000
      - SECRET=${SECRET}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - TOPIC_PREFIX=${TOPIC_PREFIX}

networks:
  proxy:
    external: true